### ISSUE TITLE
APIs are deprecated when will be updated with new?

### ISSUE THREAD

**Issue by MiteshGohil7** [FranzDiebold/ng-google-sheets-db-library#12]
Hi there,

I am trying to use your library and it works fine but sometimes this **API gives a 404**
**https://spreadsheets.google.com/feeds/list/{worsheetId}/1/public/values?alt=json**

I was trying to figure out the reason and found that it seems deprecated now as per this doc
**https://developers.google.com/sheets/api/v3/data**

so is that really deprecated that's why it gives sometimes 404 and sometimes it's working and in the past few days those 404 really increased a lot.

or is there something else issue?

can you help me with this issue?

Thanks,
Mitesh

**Comment by RicardoBorgesGO** [comment]
+1

**Comment by FranzDiebold** [comment]
Hi!

Google seems to gradually drop support for the Google Sheets "feed", which leads to 404s from time to time 😞.

Thus, I changed the lib to use the **Google Sheets API v4**! The lib is now available in version [v2.0.0](https://github.com/FranzDiebold/ng-google-sheets-db-library/releases/tag/v2.0.0) :tada:
