### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by belenofonte** [FranzDiebold/ng-google-sheets-db-library#15]
For me i think the parameters are good configured on environment.ts fille but show to me this return message the call to the google sheet:

message: "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."
status: "UNAUTHENTICATED"

Any Idea what its bad configured ?

**Comment by belenofonte** [comment]
Yes, i follow all the instructions and get the api key proberly. but fail in the get 
{
  "error": {
    "code": 403,
    "message": "Requests from referer \u003cempty\u003e are blocked.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_HTTP_REFERRER_BLOCKED",
        "domain": "googleapis.com",
        "metadata": {
          "consumer": "projects/155477220882",
          "service": "sheets.googleapis.com"
        }
      }
    ]
  }
}


in chrome inspector:

Failed to load resource: the server responded with a status of 401 ()
google-sheets-db.service.ts:193 Backend returned code 401, body was: [object Object]
handleError @ google-sheets-db.service.ts:193

**Comment by FranzDiebold** [comment]
How do the settings in the Google Cloud Platform Console for the API key look like? ([https://console.cloud.google.com/apis/credentials](https://console.cloud.google.com/apis/credentials))

In the "**Application restrictions**" you should either choose `None` or `HTTP referrers (web sites)` with `localhost` for local development and/or the URL your webapp will be deployed to:

<img width="572" alt="GCP_API_Key" src="https://user-images.githubusercontent.com/35296779/139906737-881e8675-3f95-4cf9-b630-7cc49f7b009b.png">

**Comment by belenofonte** [comment]
Sure, i tried this configuration point but the same, and open to all only for test but the same too. My organizacion user profile for enterprise not allow publish for all web, only for corporate users, so i suppose by the message: 

"message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",

Its needed some OAuth 2 authentication to access, i'll try more to find some solutions to this.

Thanks for your help.

...with the api "try" on this link... works fine but i suppose its for getting the OAuth 2 added to the call in some way.

https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/get?apix=true&apix_params=%7B%22spreadsheetId%22%3A%221loan_qtaTiF3km3Gfz6JTGORPXa-CNMBgRacY1JIZo4%22%7D

You know how to add the validation gapi to angular in properly format to call this GSheets Api?.

**Comment by FranzDiebold** [comment]
The case with restrictions in *enterprise accounts* happens quite often.
In this case, you may try to use a _private account_ without these restrictions.
