### ISSUE TITLE
Error while installing package to angular 13

### ISSUE THREAD

**Issue by 123rajneesh** [FranzDiebold/ng-google-sheets-db-library#19]
Please help to get it resolve. Thanks

npm ERR! While resolving: easytolearn@0.0.0
npm ERR! Found: @angular/common@13.3.11
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.3.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^10.2.5" from ng-google-sheets-db@2.0.0
npm ERR! node_modules/ng-google-sheets-db
npm ERR!   ng-google-sheets-db@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by FranzDiebold** [comment]
Hi @123rajneesh ,

this is not a problem of the `ng-google-sheets-db` library, but probably an npm problem.

Have you tried deleting the `package-lock.json` file and the `node_modules` folder and running `npm install` again?
