### ISSUE TITLE
Get sheet data without Active field

### ISSUE THREAD

**Issue by faizan-abdul-haq** [FranzDiebold/ng-google-sheets-db-library#20]
Hey, firstly brilliant project.
My question is that in 

```typescript
this.googleSheetsDbService
    .getActive(
      'sheetID', 
      'SheetName', 
      AttributesMapping, 
      'Active'
 );
```
 
 is Active required??
 What if I don't want active column in google sheet and get all rows?

**Comment by FranzDiebold** [comment]
Hi @faizan-abdul-haq !

In the [`getActive`](https://github.com/FranzDiebold/ng-google-sheets-db-library#getactivespreadsheetid-string-worksheetname-string-attributesmapping-object--string-isactivecolumnname-string--is_active-activevalues-string--string--null-observablet) method the `isActiveColumnName` parameter is *optional* and defaults to the value `'is_active'`.

If you want to get **all rows**, you can just use the [`get`](https://github.com/FranzDiebold/ng-google-sheets-db-library#getspreadsheetid-string-worksheetname-string-attributesmapping-object--string-observablet) method.
In your case that would mean:

```typescript
this.googleSheetsDbService
    .get(
      spreadsheetId, 
      worksheetName, 
      attributesMapping
 );
```

You can find the documentation for the two methods here: https://github.com/FranzDiebold/ng-google-sheets-db-library#methods

Happy coding! :rocket:
