### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by deviant32** [FranzDiebold/ng-google-sheets-db-library#3]
I am getting a CORS error trying to make a request from localhost.  Also how should you publish the spreadsheet?  Website, csv, ....?

**Comment by FranzDiebold** [comment]
Hi @deviant32 !

I'm happy to help!

#### 1. CORS error:
I never had CORS issues with data from Google Sheets. I just tried it out with different browsers (on macOS).
Have you published the spreadsheet correctly? Is the spreadsheet id correct?
You may also want to test the request *directly* in the browser:
 `https://spreadsheets.google.com/feeds/list/<YOUR_SPREADSHEET_ID>/1/public/values?alt=json`, i.e.  [`https://spreadsheets.google.com/feeds/list/1gSc_7WCmt-HuSLX01-Ev58VsiFuhbpYVo8krbPCvvqA/1/public/values?alt=json`]( https://spreadsheets.google.com/feeds/list/1gSc_7WCmt-HuSLX01-Ev58VsiFuhbpYVo8krbPCvvqA/1/public/values?alt=json)

#### 2. Publishing the spreadsheet:
You need to first "Publish to the web":

![](https://github.com/FranzDiebold/ng-google-sheets-db-library/raw/master/images/google-sheets-publish-1.png)

And then "Entire Document" & "Webpage".

![](https://github.com/FranzDiebold/ng-google-sheets-db-library/raw/master/images/google-sheets-publish-2.png)

I will probably improve the documentation regarding this.

**Comment by deviant32** [comment]
It appears that Google has updated their sheets API to no longer support CORS.  I believe it is working for you since your document is still on the older version of their sheets API.

I can see my data fine when I hit the URL directly, but when your library tries to make the request I get the following:

![Screen Shot 2020-09-03 at 2 00 38 PM](https://user-images.githubusercontent.com/4390273/92150771-ef893480-eded-11ea-9aeb-c52d420aed74.png)

**Comment by FranzDiebold** [comment]
Thanks for the screenshot @deviant32 !

Are you really sure that you published the spreadsheet? Try to access it from a browser where you are *not logged in with your Google account*. I copied the spreadsheet Id (is the following correct? https://spreadsheets.google.com/feeds/list/1kkOO3MQubD5FC9gp-wwI2Q--t6bINX67UX9TAqBx_U0/1/public/values?alt=json), but I cannot access it and get redirected to the Google login. It seems that you did not publish the spreadsheet.

I just tested the workflow:
If I try to load an *unpublished* spreadsheet, I also get a CORS error and get redirected to `https://accounts.google.com/ServiceLogin?<and_so_on...>`. The same redirect happens in your case, see your screenshot.
But as soon as I *publish* the spreadsheet - even a newly created - the **CORS error disappears**.

**Comment by deviant32** [comment]
Yeah everything is published:

![Screen Shot 2020-09-03 at 3 02 02 PM](https://user-images.githubusercontent.com/4390273/92156147-8f4ac080-edf6-11ea-95ae-b54609a1986a.png)

**Comment by deviant32** [comment]
It looks like I found the issue, it's your account settings requiring them to be signed in.

**Comment by FranzDiebold** [comment]
I still cannot access https://spreadsheets.google.com/feeds/list/1kkOO3MQubD5FC9gp-wwI2Q--t6bINX67UX9TAqBx_U0/1/public/values?alt=json without login screen.
But I just see in your "Publish to the web" screenshot, that there is a checkmark "Require viewers to sign in with their Motion Intelligence Inc. account". This might be the problem.

**Comment by kajalmhatre-ia** [comment]
Hi @FranzDiebold, I am still getting the cors error in my angular app while accessing the sheet from my localhost...I have even publish the sheet to web
![error](https://user-images.githubusercontent.com/80770482/116886217-6d843080-ac46-11eb-9fa1-4333f8b64596.png)


![error](https://user-images.githubusercontent.com/80770482/116886070-40d01900-ac46-11eb-92aa-420d1ac1af5c.png)
