### ISSUE TITLE
Accented characters, are they alowed?

### ISSUE THREAD

**Issue by macaranduba** [FranzDiebold/ng-google-sheets-db-library#6]
Hi!

I'm having dificulty acessing columns with accented characteres like "TÍTULO". Is this supported or must headers be free of this kind of characteres like 'á'?

Here is my entity and attributes mapping structures.

```
export interface Article {
  semana: number;
  data_informe: string;
  ID: string;
  excluir: string;
  autores: string;
  tipo_estudo: string;
  data_publ: string;
  tecnologias: string;
  //titulo: string;
}

export const articleAttributesMapping = {
  semana: 'SEM.',
  data_informe: "DATA do INFORME",
  ID: 'ID',
  EXCLUIR: 'EXCLUIR?',
  autores: 'AUTORES',
  tipo_estudo: 'TIPO de ESTUDO',
  titulo: 'TITULO',
  data_publ: 'DATA PUBL',
  tecnologias: 'ESPECIFICAÇÃO da TECNOLOGIA',
};
```
Thanks for all the help you can provide!

**Comment by FranzDiebold** [comment]
Hi @macaranduba,

thanks for your comment!
You are right, accented characters were not accepted.

However, I added support for non-ASCII column names in [v1.1.0](https://github.com/FranzDiebold/ng-google-sheets-db-library/releases/tag/v1.1.0) (#7), so your use case should work now! 🎉 

Have fun using [ng-google-sheets-db](https://www.npmjs.com/package/ng-google-sheets-db) and happy coding! 🚀

**Comment by macaranduba** [comment]
Wow! I was not expecting a change in the library. I was thinking in changing my columns headers.
Thank you so much!
