### ISSUE TITLE
[Not an issue] Number vs string types

### ISSUE THREAD

**Issue by macaranduba** [FranzDiebold/ng-google-sheets-db-library#8]
Sorry Franz, but I don't know other way of contact you without opening this issue.
It's not an issue, rather a silly JavaScript/TypeScript doubt that I stumble on, for which I have a workaround but I would apreciate if you could spare some of our knowlegde with me.

I was declaring my sheet's data interface with some field columns with type other than `string`, like `semana: number; `.
I would never guess that, in Angular's TypeScript environment, my whole program would run flawlessy holding string values in the Article.semana number-typed property! But actually it does! 
Further in my code, I'm using ExcelJS to export an archive and I realise that, after fetching the google sheet I need to archive.semana = parseInt(archive.semana) and voilá: article.semana passes to hold a number instead of a string.

So, could you help me with the following 2 questions?
1) ng-google-sheets-db-library package will always return a sequence of characters, no matter the type we declare in the data interface?
2) how can a object's property of type number can hold a string without an error being thrown during execution of the JavaScript/TypeScript code?
```
export interface Article {
  semana: number;
  data_informe: string;
  ID: string;
  excluir: string;
  autores: string;
  titulo: string;
  tecnologias: string;
  sumario_achados: string;
  aval_qual_metod: string;
  resumo: string;
  referencia_bibliografica: string;
  país: string;
  NE: number;
  URL: string;

  tipo_estudo: string;
  data_publ: string;
}


export const articleAttributesMapping = {
  semana: 'SEM.',
  data_informe: 'DATA do INFORME',
  ID: 'ID',
  excluir: 'EXCLUIR?',
  autores: 'AUTORES',
  titulo: 'TÍTULO',
  tecnologias: 'ESPECIFICAÇÃO da TECNOLOGIA',
  sumario_achados: 'SUMÁRIO dos ACHADOS',
  aval_qual_metod: 'AVALIAÇÃO da QUALIDADE METODOLÓGICA',
  resumo: 'RESUMO',
  referencia_bibliografica: 'REFERÊNCIA (Vancouver)',
  país: 'PAÍS',
  NE: 'NÍVEL de EVIDÊNCIA',
  URL: 'URL',

  tipo_estudo: 'TIPO de ESTUDO',
  data_publ: 'DATA PUBL',
};
```

Thank you very much for your time!
José

**Comment by FranzDiebold** [comment]
Hi @macaranduba ,

I am happy to help you answering your questions:
In this case, the difference between TypeScript and JavaScript is important: You develop your Angular app in TypeScript. However, it is run in the browser, which can only run JavaScript. When building the Angular app, the TypeScript code is *transpiled* into JavaScript. In this process, all types you defined in TypeScript (i.e. typed variables, interfaces, ect.) are basically removed. Hence, when you run the (JavaScript) code, there are no types and thus no type problems can occur during runtime.

Regarding your questions:

1. Yes, `ng-google-sheets-db-library` package will return objects with strings. The library cannot infer the types in the interface, thus no types can be converted. However, you may do the following:

```typescript
import { Observable } from "rxjs";
import { map } from "rxjs/operators";

// ...

const articles: Article[] = this.googleSheetsDbService
    .get<Article>(
      environment.articles.spreadsheetId,
      environment.articles.worksheetId,
      articleAttributesMapping
    )
    .pipe(
      map((articles: Article[]) =>
        articles.map((article: Article) => {
          article.semana = Number(article.semana);
          article.NE = Number(article.NE);
          return article;
      })
    )
  )
```

2. During execution, no types exist any more. Thus, these type errors cannot occur during runtime, but only during the build process.

I hope this helps! 😄

If your questions are answered, you may close this issue. :wink:

**Comment by macaranduba** [comment]
Thank you so much for your time and explanations!
