### ISSUE TITLE
blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by manel00** [FranzDiebold/ng-google-sheets-db-library#9]
Hello!

I am facing this problem using your library and would like please if you can help me out to solve it, cannot understand where it comes from

Thank you

Regards

```
Access to XMLHttpRequest at 'https://accounts.google.com/ServiceLogin?service=wise&passive=1209600&continue=https://spreadsheets.google.com/feeds/list/------/-------/public/values?alt%3Djson&followup=https://spreadsheets.google.com/feeds/list/------/------/public/values?alt%3Djson&ltmpl=sheets' (redirected from 'https://spreadsheets.google.com/feeds/list/-----/-----/public/values?alt=json') from origin 'http://localhost:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

```

**Comment by FranzDiebold** [comment]
Hi @manel00,

I am happy to help you! 💪

There was a similar issue a while ago, see issue https://github.com/FranzDiebold/ng-google-sheets-db-library/issues/3:
- Did you correctly publish your spreadsheet ("Publish to the web")? You may check my answer from the other issue: https://github.com/FranzDiebold/ng-google-sheets-db-library/issues/3#issuecomment-686649293.
- Is it some kind of organisation account you are using? Is there a checkmark "Require viewers to sign in with their *** account" when trying to publish the spreadsheet?

**Comment by manel00** [comment]
Hello sir,

I am so sorry still not working... It is already published but still CORS error, can you help me through LinkedIn? Thank you

**Comment by FranzDiebold** [comment]
@manel00 Can I close the issue then?
